In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
vocab_size = 10000  

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One-hot Representation
one_hot_repr = [one_hot(word, vocab_size) for word in sent]
one_hot_repr

[[5305, 7574, 3879, 9670],
 [5305, 7574, 3879, 7723],
 [5305, 1177, 3879, 5098],
 [3744, 9957, 4630, 9721, 992],
 [3744, 9957, 4630, 9721, 746],
 [6649, 5305, 9303, 3879, 3308],
 [2329, 1243, 4727, 9721]]

In [7]:
## Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [8]:
import numpy as np

In [10]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs
print(embedded_docs)

[[   0    0    0    0 5305 7574 3879 9670]
 [   0    0    0    0 5305 7574 3879 7723]
 [   0    0    0    0 5305 1177 3879 5098]
 [   0    0    0 3744 9957 4630 9721  992]
 [   0    0    0 3744 9957 4630 9721  746]
 [   0    0    0 6649 5305 9303 3879 3308]
 [   0    0    0    0 2329 1243 4727 9721]]


In [ ]:
## Feature representation
dim=10 #dimension of the embedding


In [12]:
model= Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')    

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)  # This will give you the embedding representation of the input sentences

1/1 [==============================] - 0s 92ms/step


array([[[ 0.03901274, -0.02610322,  0.03452123, -0.0297997 ,
         -0.03315693,  0.00645167, -0.04879503,  0.02375105,
         -0.01346433, -0.03295237],
        [ 0.03901274, -0.02610322,  0.03452123, -0.0297997 ,
         -0.03315693,  0.00645167, -0.04879503,  0.02375105,
         -0.01346433, -0.03295237],
        [ 0.03901274, -0.02610322,  0.03452123, -0.0297997 ,
         -0.03315693,  0.00645167, -0.04879503,  0.02375105,
         -0.01346433, -0.03295237],
        [ 0.03901274, -0.02610322,  0.03452123, -0.0297997 ,
         -0.03315693,  0.00645167, -0.04879503,  0.02375105,
         -0.01346433, -0.03295237],
        [-0.03057124, -0.04056365,  0.02419362,  0.00034374,
         -0.01660914,  0.02117051,  0.02354628, -0.03907089,
          0.00359096, -0.03005996],
        [-0.00149944, -0.00495777, -0.00878023,  0.03112311,
          0.03246838,  0.04127188,  0.02761761,  0.04650411,
         -0.00062058,  0.0140951 ],
        [ 0.01778101,  0.00721965, -0.04907494, -0.0